version: '3.6'
services:
  crypto-news:
    container_name: crypto-news
    image: devopssf/crypto-news:latest
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    restart: always
    volumes:
      - ./:/crypto-news
    ports:
      - "8000:8000"